---
 - name:  provisioning a new EC2 using Ansible playbook
   hosts: localhost
   connection: local
   gather_facts: False
   tags: provisioning

   vars:
     keypair: PoC_Key_Pair
     instance_type: t2.micro
     image: ami-0ee23bfc74a881de5
     wait: yes
     group: webserver
     count: 1
     region: eu-north-1b
     security_group: launch-wizard-1  
     
     - name: Launch the new EC2 Instance
       local_action:  ec2 
                      group={{ security_group }} 
                      instance_type={{ instance_type}} 
                      image={{ image }} 
                      wait=true 
                      region={{ region }} 
                      keypair={{ keypair }}
                      count={{count}}
       register: ec2
       
     - name: Task # 3 Add Tagging to EC2 instance
       local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
       with_items: "{{ ec2.instances }}"
       args:
         tags:
           Name: PoC_Child_1
           Service: Proof of Concept
           Environment: Sandbox
           Role: Child Instance
           Team: DevOps
